# cloudbuild.yaml

steps:
  # 1. Construir la imagen del contenedor Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/agente-ia-docs:${COMMIT_SHA}'
      - '.'
    id: 'Build'

  # 2. Subir la imagen a Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/agente-ia-docs:${COMMIT_SHA}'
    id: 'Push'

  # 3. Desplegar la imagen en Cloud Run
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'agente-ia-docs' # <-- Nombre de tu servicio en Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/agente-ia-docs:${COMMIT_SHA}'
      - '--region'
      - 'us-central1' # <-- Cambia a tu región preferida
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # <-- Permite el acceso público a la interfaz web
      - '--quiet'
    id: 'Deploy'

# Especifica la imagen final para que aparezca en los detalles de la compilación.
images:
  - 'gcr.io/$PROJECT_ID/agente-ia-docs:${COMMIT_SHA}'